AdminStore/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminStore.Areas.Identity.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AdminStore/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace AdminStore.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;

        public ConfirmEmailModel(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ConfirmEmailAsync(user, code);
            StatusMessage = result.Succeeded ? "Thank you for confirming your email." : "Error confirming your email.";
            return Page();
        }
    }
}

AdminStore/Areas/Identity/Pages/Account/ConfirmEmailChange.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace AdminStore.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ConfirmEmailChangeModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public ConfirmEmailChangeModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(string userId, string email, string code)
        {
            if (userId == null || email == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ChangeEmailAsync(user, email, code);
            if (!result.Succeeded)
            {
                StatusMessage = "Error changing email.";
                return Page();
            }

            // In our UI email and user name are one and the same, so when we update the email
            // we need to update the user name.
            var setUserNameResult = await _userManager.SetUserNameAsync(user, email);
            if (!setUserNameResult.Succeeded)
            {
                StatusMessage = "Error changing user name.";
                return Page();
            }

            await _signInManager.RefreshSignInAsync(user);
            StatusMessage = "Thank you for confirming your email change.";
            return Page();
        }
    }
}

AdminStore/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace AdminStore.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                await _emailSender.SendEmailAsync(
                    Input.Email,
                    "Reset Password",
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

AdminStore/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminStore.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AdminStore/Areas/Identity/Pages/Account/Lockout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminStore.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AdminStore/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AdminStore.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using AdminStore.Services;

namespace AdminStore.Controllers
{
    [Authorize(Roles = "Admin, DataEntry")]
    public class SetupController : Controller
    {
        string path = "";
        private StoreKingbhaiContext db = new StoreKingbhaiContext();
        public SetupController()
        {
            getpath();
        }
        public void getpath()
        {
            PathClass obj = new PathClass();
            path = obj.getpthString();
        }
        public IActionResult Category()
        {
            return View();
        }
        public IActionResult SecondCategory()
        {
            return View();
        }
        public IActionResult ThirdCategory()
        {
            return View();
        }
        public IActionResult FourthCategory()
        {
            return View();
        }
        public IActionResult UOM()
        {
            return View();
        }
        public IActionResult Country()
        {
            
            return View();
        }
        public IActionResult Region()
        {
            return View();
        }
        public IActionResult City()
        {
            return View();
        }
        public IActionResult Area()
        {
            return View();
        }
        public IActionResult Brand()
        {
            return View();
        }
        //UOM
        public async Task<string> SaveUOM(string Id, string UOM)
        {
            try
            {
                if (Id == "0")
                {
                    var n = new TblProductUnit();
                    n.UnitName = UOM;
                    db.TblProductUnit.Add(n);
                    await db.SaveChangesAsync();
                    return "true";
                }
                else
                {
                    var CID = Convert.ToDecimal(Id);
                    var get = db.TblProductUnit.FirstOrDefault(x => x.Id == CID);
                    get.UnitName = UOM;
                    db.TblProductUnit.Update(get);
                    await db.SaveChangesAsync();
                    return "updated";
                }
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        public IActionResult GetallUOM()
        {
            var get = db.TblProductUnit.ToList();
            return PartialView(get);
        }
        public string DeleteUOM(decimal Id)
        {
            try
            {
                var get = db.TblProductUnit.FirstOrDefault(x => x.Id == Id);
                db.TblProductUnit.Remove(get);
                db.SaveChanges();
                return "true";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        //catgory
        public async Task< string> SaveCategory(string Id, string Category,string ImageOne,string IsFront,string OrderBy)
        {
            try
            {
             
                if(Id=="0")
                {
                   
                    var n = new TblCategory();
                    n.CategoryName = Category;
                    if(IsFront== "on")
                    {
                        n.IsTop = true;
                    }
                    else
                    {
                        n.IsTop = false;
                    }
                    if (OrderBy != ""&&OrderBy!=null)
                    {
                        n.Orderby = Convert.ToInt32(OrderBy);
                    }
                    else
                    {
                        var getmax = db.TblCategory.Max(x => x.Orderby);
                        n.Orderby = getmax + 1;
                    }
                    n.Image = ImageOne;
                    db.TblCategory.Add(n);
                    await db.SaveChangesAsync();
                    return "true";
                }
                else
                {
                    var CID = Convert.ToDecimal(Id);
                    var get = db.TblCategory.FirstOrDefault(x => x.Id == CID);
                    get.CategoryName = Category;
                    if (IsFront == "on")
                    {
                        get.IsTop = true;
                    }
                    else
                    {
                        get.IsTop = false;
                    }
                    if (OrderBy != "" && OrderBy != null)
                    {
                       get.Orderby = Convert.ToInt32(OrderBy);
                    }
                    else
                    {
                        var getmax = db.TblCategory.Max(x => x.Orderby);
                        get.Orderby = getmax + 1;
                    }
                    get.Image = ImageOne;
                    db.TblCategory.Update(get);
                    await db.SaveChangesAsync();
                    return "updated";
                }
            }
            catch(Exception ex)
            {
                return ex.Message;
            }
        }
        public IActionResult GetAllCategory()
        {
            var get = db.TblCategory.ToList();
            return PartialView(get);
        }
        public string DeleteCategory(decimal Id)
        {
            try
            {
                var get = db.TblCategory.FirstOrDefault(x => x.Id == Id);
                db.TblCategory.Remove(get);
                db.SaveChanges();
                return "true";
            }
            catch(Exception ex)
            {
                return ex.Message;
            }
        }
        //Brand

        public async Task<string> SaveBrand(string Id, string Brand,string IsTop)
        {
            try
            {
                if (Id == "0")
                {
                    var n = new TblBrand();
                    n.BrandName = Brand;
                    if (IsTop == "on")
                    {
                        n.IsTop = true;
                    }
                    else
                    {
                        n.IsTop = false;
                    }
                    db.TblBrand.Add(n);
                    await db.SaveChangesAsync();
                    return "true";
                }
                else
                {
                    var CID = Convert.ToDecimal(Id);
                    var get = db.TblBrand.FirstOrDefault(x => x.Id == CID);
                    get.BrandName = Brand;
                    if (IsTop == "on")
                    {
                        get.IsTop = true;
                    }
                    else
                    {
                        get.IsTop = false;
                    }
                    db.TblBrand.Update(get);
                    await db.SaveChangesAsync();
                    return "updated";
                }
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        public IActionResult GetallBrands()
        {
            var get = db.TblBrand.ToList();
            return PartialView(get);
        }
        public string DeleteBrand(decimal Id)
        {
            try
            {
                var get = db.TblBrand.FirstOrDefault(x => x.Id == Id);
                db.TblBrand.Remove(get);
                db.SaveChanges();
                return "true";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        //////
        //country
        public async Task<string> SaveCountry(string Id, string Country)
        {
            try
            {
                if (Id == "0")
                {
                    var n = new TblCountry();
                    n.CountryName = Country;
                    db.TblCountry.Add(n);
                    await db.SaveChangesAsync();
                    return "true";
                }
                else
                {
                    var CID = Convert.ToDecimal(Id);
                    var get = db.TblCountry.FirstOrDefault(x => x.Id == CID);
                    get.CountryName = Country;
                    db.TblCountry.Update(get);
                    await db.SaveChangesAsync();
                    return "updated";
                }
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        public IActionResult GetallCountry()
        {
            var get = db.TblCountry.ToList();
            return PartialView(get);
        }
        public string DeleteCountry(decimal Id)
        {
            try
            {
                var get = db.TblCountry.FirstOrDefault(x => x.Id == Id);
                db.TblCountry.Remove(get);
                db.SaveChanges();
                return "true";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        //////
      
            //Region

        public async Task<string> SaveRegion(string Id, string Country,string Region)
        {
            try
            {
                if (Id == "0")
                {
                    var n = new TblRegion();
                    n.CountryId = Convert.ToDecimal(Country);
                    n.RegionName = Region;
                    db.TblRegion.Add(n);
                    await db.SaveChangesAsync();
                    return "true";
                }
                else
                {
                    var CID = Convert.ToDecimal(Id);
                    var get = db.TblRegion.FirstOrDefault(x => x.Id == CID);
                    get.CountryId = Convert.ToDecimal(Country);
                    get.RegionName = Region;

AdminStore/Views/Setup/Area.cshtml
@using AdminStore.Models;
@{
    StoreKingbhaiContext db = new StoreKingbhaiContext();
    ViewData["Title"] = "Area";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
    var getallCountry = db.TblCountry.ToList();
}

@section Scripts{
    <script src="~/js/Setup/Address/Area.js"></script>

    <script src="~/js/Setup/Address/Common.js"></script>
}
<input type="hidden" id="RegionId" value="0" />
<input type="hidden" id="CityId" value="0" />
<input type="hidden" id="GetallCityDRPURL" value="@Url.Action("GetallCityDRP","Setup")" />

<input type="hidden" id="GetallRegionDRPURL" value="@Url.Action("GetallRegionDRP","Setup")" />

<input type="hidden" id="SaveURL" value="@Url.Action("SaveArea","Setup")" />
<input type="hidden" id="GetallURL" value="@Url.Action("GetallArea","Setup")" />
<input type="hidden" id="DeleteURL" value="@Url.Action("DeleteArea","Setup")" />

<input type="hidden" id="Id" value="0" />
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>
                        Setup

                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">

                    <li class="breadcrumb-item">Setup</li>
                    <li class="breadcrumb-item active">Address</li>
                    <li class="breadcrumb-item active">Area</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card tab2-card">
                <div class="card-header">
                    <h5>Add Area</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Country</label>
                                <select class="form-control" id="Country" onchange="GetallRegionDRP()">
                                    <option>--Select Country--</option>
                                    @foreach (var item in getallCountry)
                                    {
                                        <option value="@item.Id">@item.CountryName</option>
                                    }
                                </select>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Region</label>
                                <select class="form-control" id="Region" onchange="GetallCityDRP()">
                                    <option>--Select Region--</option>

                                </select>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>City</label>
                                <select class="form-control" id="City">
                                    <option>--Select City--</option>

                                </select>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Area Name</label>
                                <input type="text" id="AreaName" class="form-control" />
                                <span id="CategoryErrorField" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary" onclick="SaveCity()">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h5>Category List</h5>
        </div>
        <div class="card-body" id="DataHtml">

        </div>
    </div>
</div>

AdminStore/Views/Setup/City.cshtml
@using AdminStore.Models;
@{
    StoreKingbhaiContext db = new StoreKingbhaiContext();
    ViewData["Title"] = "City";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
    var getallCountry = db.TblCountry.ToList();
}

@section Scripts{
    <script src="~/js/Setup/Address/City.js"></script>

    <script src="~/js/Setup/Address/Common.js"></script>
}
<input type="hidden" id="RegionId" value="0" />
<input type="hidden" id="SaveURL" value="@Url.Action("SaveCity","Setup")" />
<input type="hidden" id="GetallURL" value="@Url.Action("GetallCity","Setup")" />
<input type="hidden" id="DeleteURL" value="@Url.Action("DeleteCity","Setup")" />
<input type="hidden" id="GetallRegionDRPURL" value="@Url.Action("GetallRegionDRP","Setup")" />

<input type="hidden" id="Id" value="0" />
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>
                        Setup

                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">

                    <li class="breadcrumb-item">Setup</li>
                    <li class="breadcrumb-item active">Address</li>
                    <li class="breadcrumb-item active">City</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card tab2-card">
                <div class="card-header">
                    <h5>Add City</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Country</label>
                                <select class="form-control" id="Country" onchange="GetallRegionDRP()">
                                    <option>--Select Country--</option>
                                    @foreach (var item in getallCountry)
                                    {
                                        <option value="@item.Id">@item.CountryName</option>
                                    }
                                </select>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Region</label>
                                <select class="form-control" id="Region">
                                    <option>--Select Region--</option>

                                </select>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>City Name</label>
                                <input type="text" id="City" class="form-control" />
                                <span id="CategoryErrorField" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary" onclick="SaveCity()">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h5>Category List</h5>
        </div>
        <div class="card-body" id="DataHtml">

        </div>
    </div>
</div>

AdminStore/Views/Setup/FourthCategory.cshtml
@using AdminStore.Models;
@{
    StoreKingbhaiContext db = new StoreKingbhaiContext();
    ViewData["Title"] = "Fourth Category";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
    var getallCategory = db.TblCategory.ToList();
}

@section Scripts{
    <script src="~/js/Setup/Category/FourthCategory.js"></script>
    <script src="~/js/Setup/Category/Common.js"></script>

}
<input type="hidden" id="SaveURL" value="@Url.Action("SaveFourthCategory","Setup")" />
<input type="hidden" id="GetallURL" value="@Url.Action("GetallFourthCategory","Setup")" />
<input type="hidden" id="DeleteURL" value="@Url.Action("DeleteFourthCategory","Setup")" />

<input type="hidden" id="GetSecondCategoryDRPURL" value="@Url.Action("GetSecondCategoryDRP","Setup")" />
<input type="hidden" id="GetThirdCategoryDRPURL" value="@Url.Action("GetThirdCategoryDRP","Setup")" />
<input type="hidden" id="GetFourthCategoryDRPURL" value="@Url.Action("GetFourthCategoryDRP","Setup")" />


<input type="hidden" id="HideSecondCategoryId" value="0" />
<input type="hidden" id="HideThirdCategoryId" value="0" />


<input type="hidden" id="Id" value="0" />
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>
                        Setup

                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">

                    <li class="breadcrumb-item">Category</li>

                    <li class="breadcrumb-item active">Fourth Category</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card tab2-card">
                <div class="card-header">
                    <h5>Add Fourth Category</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Category</label>
                                <select class="form-control" id="Category" onchange="GetSecondCategoryDRP()">
                                    <option>--Select Category--</option>
                                    @foreach (var item in getallCategory)
                                    {
                                        <option value="@item.Id">@item.CategoryName</option>
                                    }
                                </select>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Second Category Name</label>
                                <select class="form-control" id="SecondCategory" onchange="GetThirdCategoryDRP()">
                                    <option>--Select Second Category--</option>

                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Third Category</label>
                                <select class="form-control" id="ThirdCategory">
                                    <option>--Select Third Category--</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Fourth Category Name</label>
                                <input type="text" id="ForthCategoryName" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary" onclick="Save()">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h5>Category List</h5>
        </div>
        <div class="card-body" id="DataHtml">

        </div>
    </div>
</div>

AdminStore/Views/Setup/GetallArea.cshtml
@{
    Layout = null;
}
@model IEnumerable<AdminStore.Models.TblArea>
@using AdminStore.Models
<table class="display vendor-table" id="basic-1">
    <thead>
        <tr>
            <th>Country Name</th>
            <th>Region Name</th>
            <th>City Name</th>
            <th>Area Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            StoreKingbhaiContext db = new StoreKingbhaiContext();
            
            var getCity = db.TblCity.FirstOrDefault(x => x.Id == item.CityId);
            var getregion = db.TblRegion.FirstOrDefault(x => x.Id == getCity.RegionId);
            var getcountry = db.TblCountry.FirstOrDefault(x => x.Id == getregion.CountryId);
        <tr>
            <td>
                @getcountry.CountryName
            </td>
            <td>
                @getregion.RegionName
            </td>
            <td>
                @getCity.CityName
            </td>
            <td>
                @item.AreaName
            </td>
            <td>
                <div>
                    <i class="fa fa-edit mr-2 font-success" style="cursor:pointer" onclick="Edit('@item.Id','@getcountry.Id', '@getregion.Id','@getCity.Id','@item.AreaName')"></i>
                    <i class="fa fa-trash font-danger" style="cursor:pointer" onclick="Delete('@item.Id')"></i>
                </div>
            </td>
        </tr>
        }


    </tbody>
</table>