AdminStore/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AdminStore.Models;
using Microsoft.AspNetCore.Authorization;
using AdminStore.Services;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Text.Json;
namespace AdminStore.Controllers
{
    [Authorize(Roles = "Admin, DataEntry")]
    public class SliderController : Controller
    {
        string path = "";
        private StoreKingbhaiContext db = new StoreKingbhaiContext();
        public SliderController()
        {
            getpath();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SubSlider()
        {
            return View();
        }
        public IActionResult WebReviews()
        {
            return View();
        }
        public IActionResult DiscountBanner()
        {
            return View();
        }
        public void getpath()
        {
            PathClass obj = new PathClass();
            path = obj.getpthString();
        }
        public async Task< string> SaveMainSlider(string Id, string Title, string Subtitle, string Description, string Link, string ImageOne, string ImageTwo)
        {
            string res = "";
            try
            {
                if(Id=="0")
                {
                    var s = new TblMainbanner();
                    s.Title = Title;
                    s.SubTitle = Subtitle;
                    s.Description = Description;
                    s.Link = Link;
                    s.FirstImage = ImageOne;
                    s.SecondImage = ImageTwo;
                    db.TblMainbanner.Add(s);
                    await db.SaveChangesAsync();

                    res = "true";
                }
                else
                {
                    var SId = Convert.ToDecimal(Id);
                    var s = db.TblMainbanner.FirstOrDefault(x=>x.Id== SId);
                    s.Title = Title;
                    s.SubTitle = Subtitle;
                    s.Description = Description;
                    s.Link = Link;
                    s.FirstImage = ImageOne;
                    s.SecondImage = ImageTwo;
                    db.TblMainbanner.Update(s);
                    await db.SaveChangesAsync();
                    res = "updated";
                }
              
            }
            catch(Exception ex)
            {
                res = ex.Message;
            }
            return res;
        }
        public IActionResult EditMainSlider(decimal Id)
        {
            var s = db.TblMainbanner.FirstOrDefault(x => x.Id == Id);
            return Json(new { s });
        }
        public string DeleteMainSlider(decimal Id)
        {
            try
            {
                var s = db.TblMainbanner.FirstOrDefault(x => x.Id == Id);
                db.TblMainbanner.Remove(s);
                db.SaveChanges();
                return "true";
            }
            catch(Exception ex)
            {
                return ex.Message;
            }
           
        }
        public async Task<string> SaveSubSlider(string Id, string Title, string Subtitle, string Position, string Link, string ImageOne)
        {
            string res = "";
            try
            {
                if (Id == "0")
                {
                    var s = new TblSubbanners();
                    s.Title = Title;
                    s.SubTitle = Subtitle;
                    if (Position== "Top")
                    {
                        s.IsBottom = false ;
                        s.IsTop = true;
                    }
                    if (Position == "Bottom")
                    {
                        s.IsBottom = true;
                        s.IsTop = false;

                    }
                 
                    s.Link = Link;
                    s.Image = ImageOne;
                    db.TblSubbanners.Add(s);
                    await db.SaveChangesAsync();

                    res = "true";
                }
                else
                {
                    var SId = Convert.ToDecimal(Id);
                    var s = db.TblSubbanners.FirstOrDefault(x => x.Id == SId);
                    
                    s.Title = Title;
                    s.SubTitle = Subtitle;
                    if (Position == "Top")
                    {
                        s.IsBottom = false;
                        s.IsTop = true;
                    }
                    if (Position == "Bottom")
                    {
                        s.IsBottom = true;
                        s.IsTop = false;

                    }

                    s.Link = Link;
                    s.Image = ImageOne;
                    db.TblSubbanners.Update(s);
                    await db.SaveChangesAsync();
                    res = "updated";
                }

            }
            catch (Exception ex)
            {
                res = ex.Message;
            }
            return res;
        }
        public IActionResult EditSubSlider(decimal Id)
        {
            var s = db.TblSubbanners.FirstOrDefault(x => x.Id == Id);
            return Json(new { s });
        }
        public string DeleteSubSlider(decimal Id)
        {
            try
            {
                var s = db.TblSubbanners.FirstOrDefault(x => x.Id == Id);
                db.TblSubbanners.Remove(s);
                db.SaveChanges();
                return "true";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

        }

        public async Task<string> SaveDiscountBanner(string Id, string Title, string Link, string ImageOne)
        {
            string res = "";
            try
            {
                if (Id == "0")
                {
                    var s = new TblDiscountbanner();
                    s.Title = Title;
                  
                    s.Link = Link;
                    s.Image = ImageOne;
                 
                    db.TblDiscountbanner.Add(s);
                    await db.SaveChangesAsync();

                    res = "true";
                }
                else
                {
                    var SId = Convert.ToDecimal(Id);
                    var s = db.TblDiscountbanner.FirstOrDefault(x => x.Id == SId);
                
                    s.Title = Title;

                    s.Link = Link;
                    s.Image = ImageOne;
                    db.TblDiscountbanner.Update(s);
                    await db.SaveChangesAsync();
                    res = "updated";
                }

            }
            catch (Exception ex)
            {
                res = ex.Message;
            }
            return res;
        }
        public IActionResult EditDiscountBanner(decimal Id)
        {
            var s = db.TblDiscountbanner.FirstOrDefault(x => x.Id == Id);
            return Json(new { s });
        }
        public string DeleteDiscountBanner(decimal Id)
        {
            try
            {
                var s = db.TblDiscountbanner.FirstOrDefault(x => x.Id == Id);
                db.TblDiscountbanner.Remove(s);
                db.SaveChanges();
                return "true";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

        }

        public async Task< string> ShowFront(decimal Id)
        {
            try
            {
                var get = db.TblWebReviews.FirstOrDefault(x => x.Id == Id);
                get.IsFront = true;
                db.TblWebReviews.Update(get);
              await  db.SaveChangesAsync();
                return "true";
            }
            catch(Exception ex)
            {
                return ex.Message;
            }
           
        }
        public async Task<string> ShowNotFrontURL(decimal Id)
        {
            try
            {
                var get = db.TblWebReviews.FirstOrDefault(x => x.Id == Id);
                get.IsFront = false;
                db.TblWebReviews.Update(get);
                await db.SaveChangesAsync();
                return "true";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

        }
        public async Task<JsonResult> SaveCompanyLogo(List<IFormFile> files)
        {
            long size = files.Sum(f => f.Length);
            var UniqueName = "";
            foreach (var formFile in files)
            {

                try
                {
                    if (formFile.Length > 0)
                    {
                        string UploadsFolder = Path.Combine(path, "Images\\CompanyImages");
                        if (!Directory.Exists(UploadsFolder))
                        {
                            Directory.CreateDirectory(UploadsFolder);
                        }
                        UniqueName = Guid.NewGuid() + "_" + formFile.FileName;
                        string filePath = Path.Combine(UploadsFolder, UniqueName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await formFile.CopyToAsync(stream);
                        }
                    }
                }
                catch (Exception ex)
                {
                    return Json("");
                }

            }
            return Json("Images/CompanyImages/" + UniqueName);

        }
        public async Task<JsonResult> SaveImageOne(List<IFormFile> files)
        {
            long size = files.Sum(f => f.Length);
            var UniqueName = "";
            foreach (var formFile in files)
            {

                try
                {
                    if (formFile.Length > 0)
                    {

AdminStore/Views/Slider/DiscountBanner.cshtml
@using AdminStore.Models;
@using AdminStore.Services
@{
    StoreKingbhaiContext db = new StoreKingbhaiContext();
    ViewData["Title"] = "Discount Banner";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
    var getall = db.TblDiscountbanner.ToList();
    PathClass obj = new PathClass();
    string path = obj.GetDomainNme();

}
@section Scripts{
    <script src="~/js/Slider/DiscountBanner.js"></script>
}
<input type="hidden" id="SaveURL" value="@Url.Action("SaveDiscountBanner","Slider")" />
<input type="hidden" id="DeleteURL" value="@Url.Action("DeleteDiscountBanner","Slider")" />
<input type="hidden" id="EditURL" value="@Url.Action("EditDiscountBanner","Slider")" />
<input type="hidden" id="SaveImageOneURL" value="@Url.Action("SaveImageOne","Slider")" />


<input type="hidden" id="Id" value="0" />
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>
                        Slider

                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">

                    <li class="breadcrumb-item">Slider</li>
                    <li class="breadcrumb-item active">Discount Banner</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card tab2-card">
                <div class="card-header">
                    <h5>Add Discount Banner</h5>
                </div>
                <div class="card-body">
                    <div class="row">

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" id="Title" class="form-control" />

                            </div>
                        </div>
                        
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Link</label>
                                <input type="text" id="Link" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Image</label>
                                <input type="file" id="ImageOne" class="form-control" />

                            </div>
                        </div>

                    </div>
                    
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary" onclick="SaveDiscountBanner()">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h5>List</h5>
        </div>
        <div class="card-body">
            <table class="display vendor-table" id="basic-1">
                <thead>
                    <tr>
                        <th>Title</th>
                       
                        <th>Link</th>
                        <th>Image </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in getall)
                    {
                        <tr>
                            <td>
                                @item.Title
                            </td>
                          
                            <td>
                                @item.Link
                            </td>
                            <td>
                                @if (item.Image != null && item.Image != "")
                                {
                                    <img src="@path@item.Image" style="height:100px;width:100px;" />
                                }
                                else
                                {
                                    <img src="~/NoImage.png" style="height:100px;width:100px;" />
                                }
                            </td>

                            <td>
                                <div>
                                    <i class="fa fa-edit mr-2 font-success" style="cursor:pointer" onclick="Edit('@item.Id')"></i>
                                    <i class="fa fa-trash font-danger" style="cursor:pointer" onclick="Delete('@item.Id')"></i>
                                </div>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>
<input type="hidden" id="HideImgOneUrl" value="" />
<input type="hidden" id="HideImgTwoUrl" value="" />

<input type="hidden" id="Id" value="0" />

AdminStore/Views/Slider/Index.cshtml
@using AdminStore.Models;
@using AdminStore.Services
@{
    StoreKingbhaiContext db = new StoreKingbhaiContext();
    ViewData["Title"] = "Main Slider";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
    var getall = db.TblMainbanner.ToList();
    PathClass obj = new PathClass();
    string path = obj.GetDomainNme();

}
@section Scripts{
    <script src="~/js/Slider/MainSlider.js"></script>
}
<input type="hidden" id="SaveURL" value="@Url.Action("SaveMainSlider","Slider")" />
<input type="hidden" id="DeleteURL" value="@Url.Action("DeleteMainSlider","Slider")" />
<input type="hidden" id="EditURL" value="@Url.Action("EditMainSlider","Slider")" />
<input type="hidden" id="SaveImageOneURL" value="@Url.Action("SaveImageOne","Slider")" />
<input type="hidden" id="SaveImageTwoURL" value="@Url.Action("SaveImageTwo","Slider")" />

<input type="hidden" id="Id" value="0" />
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>
                        Slider

                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">

                    <li class="breadcrumb-item">Slider</li>
                    <li class="breadcrumb-item active">Main Slider</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card tab2-card">
                <div class="card-header">
                    <h5>Add Slider</h5>
                </div>
                <div class="card-body">
                    <div class="row">

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" id="Title" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Sub Title</label>
                                <input type="text" id="Subtitle" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Description</label>
                                <input type="text" id="Description" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Link</label>
                                <input type="text" id="Link" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Image One</label>
                                <input type="file" id="ImageOne" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Image Two</label>
                                <input type="file" id="ImageTwo" class="form-control" />

                            </div>
                        </div>
                    </div>
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary" onclick="SaveUserDetail()">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
           
        </div>
        <div class="card-body">
            <table class="display vendor-table" id="basic-1">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Sub Title</th>
                        <th>Description</th>
                        <th>Link</th>
                        <th>Image One</th>
                        <th>Image Two</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in getall)
                    {
                        <tr>
                            <td>
                                @item.Title
                            </td>
                            <td>
                                @item.SubTitle
                            </td>

                            <td>
                                @item.Description
                            </td>

                            <td>
                                @item.Link
                            </td>
                            <td>
                                @if (item.FirstImage != null)
                                {
                                    <img src="@path@item.FirstImage" style="height:100px;width:100px;" />
                                }
                                else
                                {
                                    <img src="~/NoImage.png" style="height:100px;width:100px;" />
                                }
                            </td>
                            <td>
                                @if (item.SecondImage != null)
                                {
                                    <img src="@path@item.SecondImage" style="height:100px;width:100px;" />
                                }
                                else
                                {
                                    <img src="~/NoImage.png" style="height:100px;width:100px;" />
                                }
                            </td>



                            <td>
                                <div>
                                    <i class="fa fa-edit mr-2 font-success" style="cursor:pointer" onclick="Edit('@item.Id')"></i>
                                    <i class="fa fa-trash font-danger" style="cursor:pointer" onclick="Delete('@item.Id')"></i>
                                </div>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>
<input type="hidden" id="HideImgOneUrl" value="" />
<input type="hidden" id="HideImgTwoUrl" value="" />

<input type="hidden" id="Id" value="0" />

AdminStore/Views/Slider/SubBenner.cshtml
@using AdminStore.Models;
@using AdminStore.Services
@{
    StoreKingbhaiContext db = new StoreKingbhaiContext();
    ViewData["Title"] = "Main Slider";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
    var getall = db.TblMainbanner.ToList();
    PathClass obj = new PathClass();
    string path = obj.GetDomainNme();

}
@section Scripts{
    <script src="~/js/Slider/MainSlider.js"></script>
}
<input type="hidden" id="SaveURL" value="@Url.Action("SaveMainSlider","Slider")" />
<input type="hidden" id="DeleteURL" value="@Url.Action("DeleteMainSlider","Slider")" />
<input type="hidden" id="EditURL" value="@Url.Action("EditMainSlider","Slider")" />
<input type="hidden" id="SaveImageOneURL" value="@Url.Action("SaveImageOne","Slider")" />
<input type="hidden" id="SaveImageTwoURL" value="@Url.Action("SaveImageTwo","Slider")" />

<input type="hidden" id="Id" value="0" />
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>
                        Slider

                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">

                    <li class="breadcrumb-item">Slider</li>
                    <li class="breadcrumb-item active">Main Slider</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card tab2-card">
                <div class="card-header">
                    <h5>Add Slider</h5>
                </div>
                <div class="card-body">
                    <div class="row">

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" id="Title" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Sub Title</label>
                                <input type="text" id="Subtitle" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Description</label>
                                <input type="text" id="Description" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Link</label>
                                <input type="text" id="Link" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Image One</label>
                                <input type="file" id="ImageOne" class="form-control" />

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Image Two</label>
                                <input type="file" id="ImageTwo" class="form-control" />

                            </div>
                        </div>
                    </div>
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary" onclick="SaveUserDetail()">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h5>Product List</h5>
        </div>
        <div class="card-body">
            <table class="display vendor-table" id="basic-1">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Sub Title</th>
                        <th>Description</th>
                        <th>Link</th>
                        <th>Image One</th>
                        <th>Image Two</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in getall)
                    {
                        <tr>
                            <td>
                                @item.Title
                            </td>
                            <td>
                                @item.SubTitle
                            </td>

                            <td>
                                @item.Description
                            </td>

                            <td>
                                @item.Link
                            </td>
                            <td>
                                @if (item.FirstImage != null)
                                {
                                    <img src="@path@item.FirstImage" style="height:100px;width:100px;" />
                                }
                                else
                                {
                                    <img src="~/NoImage.png" style="height:100px;width:100px;" />
                                }
                            </td>
                            <td>
                                @if (item.SecondImage != null)
                                {
                                    <img src="@path@item.SecondImage" style="height:100px;width:100px;" />
                                }
                                else
                                {
                                    <img src="~/NoImage.png" style="height:100px;width:100px;" />
                                }
                            </td>



                            <td>
                                <div>
                                    <i class="fa fa-edit mr-2 font-success" style="cursor:pointer" onclick="Edit('@item.Id')"></i>
                                    <i class="fa fa-trash font-danger" style="cursor:pointer" onclick="Delete('@item.Id')"></i>
                                </div>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>
<input type="hidden" id="HideImgOneUrl" value="" />
<input type="hidden" id="HideImgTwoUrl" value="" />

<input type="hidden" id="Id" value="0" />